export const QuizItemType = {
  QA: 'QA',
  PROPHECY: 'PROPHECY',
  BOOKS: 'BOOKS',
  HOW_TO: 'HOW_TO',
  BOOK_QUIZ: 'BOOK_QUIZ',
  MATCH_SCRIPTURE: 'MATCH_SCRIPTURE',
  FLASHCARD_MENU: 'FLASHCARD_MENU',
  ORDER_BOOKS: 'ORDER_BOOKS',
};